#!/usr/bin/env bash

###############################################################################
#                                  functions                                  #
###############################################################################
function sym_conf() {

  local src_dir="$1"
  shift
  local tar_dir="$1"
  shift

  # Don't scan for broken symlink in my home directory
  if [ "$tar_dir" != "$HOME" ]; then
    mkdir -p "$tar_dir"
    find "$tar_dir" -xtype l -exec rm -v {} \;
  fi

  # http://askubuntu.com/questions/86822/how-can-i-copy-the-contents-of-a-folder-to-another-folder-in-a-different-directo
  cp -sRvf "$src_dir/." "$tar_dir"
}
###############################################################################
#                               main function                                 #
###############################################################################
function main() {

  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  local conf_dir=${XDG_CONFIG_HOME:-$HOME/.config}
  local data_dir=${XDG_DATA_HOME:-$HOME/.local/share}

  sym_conf "${SCRIPT_DIR}/bin" "${HOME}/bin"
  sym_conf "${SCRIPT_DIR}/cookiecutter" "${HOME}"
  sym_conf "${SCRIPT_DIR}/ctags" "${HOME}"
  sym_conf "${SCRIPT_DIR}/dreamnote" "${conf_dir}/dreamnote"
  sym_conf "${SCRIPT_DIR}/git" "${conf_dir}/git"
  sym_conf "${SCRIPT_DIR}/gpg" "${HOME}/.gnupg"
  sym_conf "${SCRIPT_DIR}/liquidprompt" "${conf_dir}"
  sym_conf "${SCRIPT_DIR}/mpd" "${conf_dir}/mpd"
  sym_conf "${SCRIPT_DIR}/mpv" "${conf_dir}/mpv"
  sym_conf "${SCRIPT_DIR}/msmtp" "${HOME}"
  sym_conf "${SCRIPT_DIR}/mutt" "${HOME}/.mutt"
  sym_conf "${SCRIPT_DIR}/newsbeuter" "${conf_dir}/newsbeuter"
  sym_conf "${SCRIPT_DIR}/notmuch" "${conf_dir}/notmuch"
  sym_conf "${SCRIPT_DIR}/nvim" "${conf_dir}/nvim"
  sym_conf "${SCRIPT_DIR}/offlineimap" "${conf_dir}/offlineimap"
  sym_conf "${SCRIPT_DIR}/pam" "${HOME}"
  sym_conf "${SCRIPT_DIR}/plowshare" "${conf_dir}/plowshare"
  sym_conf "${SCRIPT_DIR}/qutebrowser" "${conf_dir}/qutebrowser"
  sym_conf "${SCRIPT_DIR}/ssh" "${HOME}/.ssh"
  sym_conf "${SCRIPT_DIR}/termite" "${conf_dir}/termite"
  sym_conf "${SCRIPT_DIR}/tmux" "${HOME}"
  sym_conf "${SCRIPT_DIR}/taskwarrior" "${conf_dir}/task"
  sym_conf "${SCRIPT_DIR}/vimpck" "${conf_dir}/vimpck"
  sym_conf "${SCRIPT_DIR}/x11" "${HOME}"
  sym_conf "${SCRIPT_DIR}/xbindkeys" "${HOME}"
  sym_conf "${SCRIPT_DIR}/zathura" "${conf_dir}/zathura"
  sym_conf "${SCRIPT_DIR}/zsh" "${conf_dir}/zsh"

  mkdir -p $(dirname "$LESSKEY")
  lesskey "${SCRIPT_DIR}/less/lesskey"
  #chmod 755 "${HOME}/.offlineimaprc"
}

###############################################################################
#                                execute main                                 #
###############################################################################
main

#TODO: mkdir ~/.local/share/newsbeuter/ <-- this xdg directory must exist if
# the configuration files are placed in ~/.config/newsbeuter/
#TODO: mkdir -p .mail here or in the post install script
# Ref: http://stackoverflow.com/questions/7470165/how-to-go-to-each-directory-and-execute-a-command
