#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

# Some applications that require X running and that should run in the background
## screensaver and lockscreen
xscreensaver -no-splash &
## load keybind defined in ~/.xbindkeysrc that enable raise lower and toggle global sound
xbindkeys -f "${XDG_CONFIG_HOME}/xbindkeys/xbindkeysrc" &
## load composite manager
compton -b &
## reduce screen luminosity
ddcutil setvcp 10 20 --bus 1 &


# Start the window manager. Line following the exec command would be ignored so don't put lines after.
exec awesome
