#!/usr/bin/env bash

# my dreamnote
local dreamnote_hook="mkdir -p $HOME/bin; "
dreamnote_hook+="ln -sfr dreamnote $HOME/bin; "
dreamnote_hook+="make venv"
nplug install -t "$dreamnote_hook" "nicodebo/dream-note"

# ohmyzsh
local ohmyzsh_hook="mkdir -p $ZDOTDIR/zcompletion; "
ohmyzsh_hook+="ln -sfr plugins/extract/_extract $ZDOTDIR/zcompletion"
nplug install -t "$ohmyzsh_hook" "robbyrussell/oh-my-zsh"

# z
nplug install "rupa/z"

# gitignore plugin
nplug install "voronkovich/gitignore.plugin.zsh"

# open git remote repo from command line
local gitopen_hook="mkdir -p $HOME/bin; "
gitopen_hook+="ln -sfr git-open $HOME/bin"
nplug install -t "$gitopen_hook" "paulirish/git-open"

# zsh-syntax-highlighting
nplug install "zsh-users/zsh-syntax-highlighting"
# zsh search
nplug install "zsh-users/zsh-history-substring-search"

# pure prompt
local pure_hook="mkdir -p $ZDOTDIR/zfunction; "
pure_hook+="ln -sfr pure.zsh $ZDOTDIR/zfunction/prompt_pure_setup; "
pure_hook+="ln -sfr async.zsh $ZDOTDIR/zfunction/async"
nplug install -t "$pure_hook" "sindresorhus/pure"
